/* eslint-disable */
// ----------------------------------------------------------------------------------------
// Do not edit this file, it is auto-generated by scripts/generate-version.js
// ----------------------------------------------------------------------------------------
export const APP_VERSION_INFO = Object.freeze({
  NAME: 'react-native-common-demo',
  DISPLAY_NAME: 'RNCommonApp',
  DESCRIPTION: 'React Native Common Kitchen Sink App',
  REPOSITORY: 'https://github.com/Lichens-Innovation/react-native-common-demo.git',
  AUTHOR: 'Lichens Innovation',
  VERSION: '1.0.0',
  RELEASE_NOTES: '',
  VERSION_DATE: '2026-01-11',
  VERSION_DATE_ISO: '2026-01-11T19:46:49.458Z',
})

export const LONG_VERSION_DATE = '1.0.0 (2026-01-11)'
